Trying a different test reporter

diff --git a/.github/workflows/container-test.yml b/.github/workflows/container-test.yml
--- a/.github/workflows/container-test.yml
+++ b/.github/workflows/container-test.yml
@@ -35,11 +35,13 @@ jobs:
       - name: Run linting and tests
         run: |
           docker run --rm -v ${{ steps.testsetup.outputs.testdir }}:"/app/test-results/" ${{ env.DOCKERHUB_REPOSITORY }}:test
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v1
-        if: always()
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          files: ${{ steps.testsetup.outputs.testdir }}**/*.xml
+          name: pytest
+          path: ${{ steps.testsetup.outputs.testdir }}**/*.xml
+          reporter: java-junit
       - name: Branch information
         id: branchinfo
         run: |
