Other test reports (#7)
* Trying a different test reporter

* Added commenting

diff --git a/.github/workflows/container-test.yml b/.github/workflows/container-test.yml
--- a/.github/workflows/container-test.yml
+++ b/.github/workflows/container-test.yml
@@ -35,11 +35,26 @@ jobs:
       - name: Run linting and tests
         run: |
           docker run --rm -v ${{ steps.testsetup.outputs.testdir }}:"/app/test-results/" ${{ env.DOCKERHUB_REPOSITORY }}:test
+
+      # EnricoMi action - https://github.com/marketplace/actions/publish-unit-test-results
+      # Nice about collapsing detailed test results, detailed instructions, supports forked repos
       - name: Publish Unit Test Results
         uses: EnricoMi/publish-unit-test-result-action@v1
         if: always()
         with:
+          check_name: pytest-results
           files: ${{ steps.testsetup.outputs.testdir }}**/*.xml
+
+      # Dorny action: https://github.com/marketplace/actions/test-reporter
+      # Accepts many input formats, good documentation of forked repos
+      # - name: Test Report -- dorny action # Accepts many input formats 
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()    # run this step even if previous step failed
+      #   with:
+      #     name: pytest
+      #     path: ${{ steps.testsetup.outputs.testdir }}**/*.xml
+      #     reporter: java-junit
+
       - name: Branch information
         id: branchinfo
         run: |
